apiVersion: apps/v1
kind: Deployment
metadata:
  name: travel-agency-backend
  labels:
    app: travel-agency-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: travel-agency-backend
  template:
    metadata:
      labels:
        app: travel-agency-backend
    spec:
      containers:
        - name: travel-agency-backend
          image: <ACR_NAME>.azurecr.io/travel-agency-backend:latest
          ports:
            - containerPort: 4000
      imagePullSecrets:
        - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: travel-agency-backend
spec:
  type: ClusterIP
  ports:
    - port: 4000
      targetPort: 4000
  selector:
    app: travel-agency-backend
