apiVersion: apps/v1
kind: Deployment
metadata:
  name: travel-agency-frontend
  labels:
    app: travel-agency-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: travel-agency-frontend
  template:
    metadata:
      labels:
        app: travel-agency-frontend
    spec:
      containers:
        - name: travel-agency-frontend
          image: <ACR_NAME>.azurecr.io/travel-agency-frontend:latest
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: travel-agency-frontend
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: travel-agency-frontend
