name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build backend Docker image
        run: docker build -t travel-agency-backend ./backend

      - name: Build frontend Docker image
        run: docker build -t travel-agency-frontend ./frontend

      - name: Run backend tests
        run: |
          cd backend
          npm install
          # Add test command if available

      - name: Run frontend tests
        run: |
          cd frontend
          npm install
          npm run build
          # Add test command if available
