name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build backend Docker image
        run: docker build -t travel-agency-backend .
        working-directory: ./backend

      - name: Build frontend Docker image
        run: docker build -t travel-agency-frontend .
        working-directory: ./frontend

      - name: List frontend directory contents (debug)
        run: ls -l
        working-directory: ./frontend

      - name: Show frontend Docker context files (debug)
        run: |
          find . -type f
        working-directory: ./frontend

      - name: Run backend tests
        run: |
          npm install
          # Add test command if available
        working-directory: ./backend

      - name: Run frontend tests
        run: |
          npm install
          npm run build
          # Add test command if available
        working-directory: ./frontend
